### ISSUE TITLE
Setup nginx, SSL and etl2.dewi.org subdomain on new ETL machine

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/dewi-etl#10]
Related to previous ticket :)

**Comment by dansku** [comment]
@jamiew  let me know when you point the subdomain to the server, I can configure nginx for it.

**Comment by jamiew** [comment]
Confirming this with @chrisbruce who is our domain admin atm, will keep you
posted

**Comment by dansku** [comment]
@jamiew i guess this one could be also closed?
