### ISSUE TITLE
Data Credit USD charts reporting inaccurate data

### ISSUE THREAD

**Issue by OrmEmbaar** [dewi-alliance/dewi-etl#18]
The dashboard displays charts showing data credit usage in USD. However, those charts appear to be off by several orders of magnitude. 

- [DC usage per week ](https://etl.dewi.org/question/32-data-credit-usage-per-week-in-usd)

![image](https://user-images.githubusercontent.com/38507729/130753803-d0a7f704-9198-4881-8533-82c490a32e8a.png)

-  [DC usage per day](https://etl.dewi.org/question#eyJuYW1lIjoiRENzIHBlciBkYXkiLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjI1LCJhZ2dyZWdhdGlvbiI6W1sic3VtIixbImV4cHJlc3Npb24iLCJVU0QiXV1dLCJicmVha291dCI6W1siZmllbGQiLDE1Nix7InRlbXBvcmFsLXVuaXQiOiJkYXkifV1dLCJmaWx0ZXIiOlsiYW5kIixbIiE9IixbImZpZWxkIiwxNTcsbnVsbF0sIjEzWmlCNzRUSk5kVjVENVZGZWhFSDNvTVN1Rk51c2praG80Z0pZbW5SbUxSblhyWmJFNSJdLFsidGltZS1pbnRlcnZhbCIsWyJmaWVsZCIsMTU2LG51bGxdLC05MCwiZGF5Iix7ImluY2x1ZGUtY3VycmVudCI6ZmFsc2V9XSxbInRpbWUtaW50ZXJ2YWwiLFsiZmllbGQiLDE1NixudWxsXSwtMzAsImRheSJdXSwiZXhwcmVzc2lvbnMiOnsiVVNEIjpbIioiLFsiZmllbGQiLDE1OCxudWxsXSwwLjAwMDAxXX19LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6ImJhciIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJncmFwaC5kaW1lbnNpb25zIjpbInRpbWUiXSwiZ3JhcGgubWV0cmljcyI6WyJzdW0iXSwiZ3JhcGgueV9heGlzLnRpdGxlX3RleHQiOiJVU0QiLCJjb2x1bW5fc2V0dGluZ3MiOnsiW1wibmFtZVwiLFwic3VtXCJdIjp7InByZWZpeCI6IiQifX0sInNlcmllc19zZXR0aW5ncyI6eyJzdW0iOnsiY29sb3IiOiIjNTA5RUUzIiwiZGlzcGxheSI6ImJhciJ9fSwiZ3JhcGguc2hvd190cmVuZGxpbmUiOmZhbHNlLCJncmFwaC5zaG93X3ZhbHVlcyI6ZmFsc2V9LCJvcmlnaW5hbF9jYXJkX2lkIjoxNzd9)

![image](https://user-images.githubusercontent.com/38507729/130753931-d43225cd-3e82-46fd-88dc-13723a90765e.png)

The explorer indicates that DC USD expenditure is currently around $2.5m USD per month. That data is corroborated by the following chart, which shows DC burn of roughly 4bn to 13bn per day. 

![image](https://user-images.githubusercontent.com/38507729/130754348-47293397-943e-4a3c-96c2-efb6c9df6fed.png)

**Comment by jamiew** [comment]
I think that last chart is showing DCs not USD, but we will investigate @wishplorer

**Comment by OrmEmbaar** [comment]
The last chart is just to illustrate the volume of DC burnt per day and how that corroborates the explorer, which reports that we're burning millions of dollars of DC per month. The first two charts suggest the number is more like a few hundred dollars per month, so obviously something doesn't add up.

**Comment by jamiew** [comment]
Ah I think I know the issue – the "DC usage per day/week" charts are just showing DCs used for actual data transfer. 

Explorer (and the last graph) are showing DCs used for any reason, including the fees for onboarding hotspots and sending payments. I think the very tiny little blue parts of that chart are DCs for data transfer

Do you think changing the title of the first two charts would sufficiently clarify?

**Comment by OrmEmbaar** [comment]
Yes, renaming them would be perfect. I had hoped to clarify how much was spent on actual data transfers so this is exactly what I need.

**Comment by jamiew** [comment]
I've renamed the data-transfer only charts to say as much

Network-fee-wise this is the more comprehensive chart:
https://etl.dewi.org/public/question/badaf90c-82ba-4597-97d0-8eab04f3c801

Editable link if you are logged in:
https://etl.dewi.org/question/158-data-credits-burned-per-day

Thanks for filing the bug report!
