### ISSUE TITLE
Setup fresh servers if needed, splitting ETL from database server

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/dewi-etl#2]
Or using hosted database server? Discused but did not reach a decision about either way

I am indifferent. I've been using self-hosted so far. Monitoring and growing disk is a chore; hosted usually can be quite fast too

**Comment by dansku** [comment]
I've done this is the part, i believe it's mostly required if the server is getting hammered. So far it's been smooth, when it gets worked we can split it into two servers.
