### ISSUE TITLE
Can't sign up - "Youll need an administrator to create a Metabase account before you can use Google to log in."

### ISSUE THREAD

**Issue by littlecluster** [dewi-alliance/dewi-etl#23]
Data does not appear to be publicly available, I receive the below error

Youll need an administrator to create a Metabase account before you can use Google to log in.

**Comment by wishplorer** [comment]
This is not the case, anyone should be able to auto signup using gmail . com email. it should not be company hosted email on gmail.

**Comment by fraggy2k** [comment]
Same issue here, tried 2 different Google accounts (one with gmail dot com address) and getting the red info message

**Comment by tr1plx** [comment]
Same issue here...

![image](https://user-images.githubusercontent.com/15807586/152190159-27e1f091-0623-46fb-8ff9-349953030193.png)

**Comment by jamiew** [comment]
@fraggy2k @tr1plx were you able to get this sorted? Could you @-mention me (jamiedubs#0001) in #data-analysis on Helium discord if not?

**Comment by jamiew** [comment]
Looks like this issue is back. Possibly expired Google credentials? I removed the /api/user block but that didn't fix it. cc @wishplorer @dansku @evandiewald

**Comment by wishplorer** [comment]
I checked everything on google cloud and on metabase side. everything seems to be fine. was it one user issue or failing for all?

**Comment by mowaxuk** [comment]
Failing for me as well. 

![2022-10-26_13-31-58](https://user-images.githubusercontent.com/52049876/198028652-9af206fd-937e-44fd-a34a-e2ebd01c606e.jpg)

**Comment by jamiew** [comment]
Final update: this is caused by using a non-`gmail.com` domain. We can only support `gmail.com` Google Accounts
