### ISSUE TITLE
Public-access/self-registration for Metabase

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/dewi-etl#6]
Or possibly look into other options? Otherwise been very impressed w/ Metabase

**Comment by wishplorer** [comment]
This is enabled via google sign in. There is still pending verification to allow for more than 100 user sign up but for that I would need help from Jamie to put verification code in a file in specific location on server for dewi.org.

**Comment by wishplorer** [comment]
After setting to in production, verification is not required. we have already seen few users logging in with google sign in. so we can consider this implementation successful and complete.

**Comment by jamiew** [comment]
Woohoo, nicely done!

**Comment by HNT-DXB** [comment]
![Screenshot 2021-10-11 095901](https://user-images.githubusercontent.com/84614441/136740374-43d99b75-9500-4d33-8d8e-09cdab1b0e95.png)
Having issues logging in via Google, any tips?
